### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [hrmeetsingh/oh-my-zsh-themes#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Finally - consider moving the theme file to the root of the repository. This will make it easier for framework users to add your theme since most ZSH frameworks will automatically find `.zsh-theme` and `.plugin.zsh` files at the root of repositories - if it isn't there, the users have to special-case adding your theme.

This also makes it better to have one repository per theme - I get that you're collecting ones that work well on dark-themed machines, but I recommend having separate repos for each theme with links to each other in their readmes.

Thanks!

**Comment by hrmeetsingh** [comment]
Thanks @unixorn , have added a separate repo for this particular theme https://github.com/hrmeetsingh/sorin-modified-dark as you suggested(with a licence and screenshot). you can us the new one. Will keep this repo to maintain a collection of themes

Thanks for the suggestion

**Comment by unixorn** [comment]
Thanks, added in https://github.com/unixorn/awesome-zsh-plugins/pull/1895. Might be easiest to make your other repos submodules here so you don't have to update your themes in multiple places.

If the description of https://github.com/hrmeetsingh/sorin-modified-dark needs tweaking, either make an issue or PR it in [unixorn/awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) directly.

**Comment by hrmeetsingh** [comment]
Thanks @unixorn , your repo is a goldmine and I'm glad that my contribution made it into it. I am tempted to try most of the themes here. Appreciate the effort you put in to maintain. Will definitely raise a PR if I have a new theme/plugin.
